### PR TITLE
Specify required arguments for Python element classes.

### PR DESCRIPTION
**Pull request by willrogers**
This afternoon's changes:

* I made required arguments explicit in the Python class constructors
* I also removed the 'name' attribute because I could not see any value in it.

@bnash @lfarv

### CODE REVIEW

**Comment by lfarv** [comment]
Oh no ! You cannot remove the name attribute !
It’s the way to locate the desired element in a list which is permanently modified. Many AT function use a “REFPTS argument ("reference points") to select where output values should be computed or attributes modified, or else… Element names are one usual way to fill these arguments.
The element name is mandatory and it should be the first argument (though an “unnamed” default value could be set, if the user uses only keyword arguments for the remaining arguments) !

Best regards

Laurent

**Comment by willrogers** [comment]
Wait, are we actually talking about 'FamName'?

**Comment by lfarv** [comment]
Well, as far as I can see, “FamName” is called “name” in pyat. We just need one of those, which should be the 1st argument in constructors. Did I mis something ?

Laurent

**Comment by willrogers** [comment]
I understand the use for family name.  I will put it back, but use the attribute `FamName` for consistency with Matlab.

**Comment by lfarv** [comment]
Good.
I keep the “lfar" branch synchronised with “pyat”. Do I understand correctly that you’ll merge “python-elements”  (or further topic branches) into “pyat" when it is stable ?

Laurent

**Comment by willrogers** [comment]
Correct.  The `python-elements` branch now has `FamName` reinstated so you can see the updated changes in this pull request.

**Pull request merged**
