### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by willrogers**
I realise there is still a problem with `at.h`.

There is one more problem to compile on Windows:  `mexErrMsgIdAndText` and `mexErrMsgTxt` in `IdTablePass.c` and `interpolate.c`.  I'm not sure how best to replace these.

### CODE REVIEW

**Comment by lfarv** [comment]
The Windows part added in atelem.c should go into the 'PYAT' section of the fiel, otherwise there is a conflict for the "bool" type defined differently in Matlab. That's what I am looking at in at.h at the moment

**Comment by lfarv** [comment]
No problem any more for me !

**Comment by willrogers** [comment]
I need help replacing the calls to `mexErrMsgIdAndText` and `mexErrMsgTxt`...

**Comment by lfarv** [comment]
I can fix this, but I need to get the last integrators from the "windows-build" before modifying. So I'll try and merge "windows-build" into "lfar", and let you know.

**Pull request merged**
