### PR TITLE
Fast integrators

### PR DESCRIPTION
**Pull request by willrogers**
Let's discuss here @lfarv @bnash @carmignani

### CODE REVIEW

**Comment by willrogers** [comment]
Laurent:

I pushed a new branch on GitHub called “fast_integrators”. It reduces the tracking time by a factor > 5 and is ~equivalent to the matlab version. This is done by storing on the first turn the pointer to the desired integrator function and the corresponding data extracted from the element object.

In addition, atpass is modified to be closer to the matlab version:
- particle coordinates are output for each turn and at points specified by a “refpts" argument (default: end of the ring)
- a keyword argument “reuse=1” allows to keep the data stored on a previous call without needing a new 1st turn storage (to be used only if nothing changed in the lattice)

The integrators are changed so that they take care of the 1st turn by allocating and filling the space used for their specific parameters. This is done so that it is compatible between matlab an python. The modified integrators are:

        BndMPoleSymplectic4FrgFPass.c
        BndMPoleSymplectic4FrgFRadPass.c
        CavityPass.c
        DriftPass.c
        IdentityPass.c
        QuadMPoleFringePass.c
        QuadMPoleFringeRadPass.c
        QuantDiffPass.c
        RFCavityPass.c
        StrMPoleSymplectic4Pass.c
        StrMPoleSymplectic4RadPass.c

        The default ones for dipoles (BendLinearPass) and quadrupoles (QuadLinearPass) are NOT yet converted !

**Comment by willrogers** [comment]
I realise that I started this by copying from `atpass.c`, but can we now take the Windows/Linux function loading code into a shared file?

**Comment by willrogers** [comment]
This is working for me.  I can't test the `load_mat.py` file yet because we don't have `BndMpoleSymplectic4E2Pass.c` converted yet.

These are now significant changes to large parts of the structure.  That's ok for me if it is for you (unless you're planning to keep the original version of AT alive as well, that would cause problems), and it means we have some freedom to do further cleaning up (e.g. removing the tabs from the source code, dropping passFunction?).

There are few things that could be tidied, such as some more consistent variable naming and some code duplication.

I'm happy to merge this if everyone else is.

**Comment by lfarv** [comment]
Everything looks fine for us at this point, including load_mat.py (and apart the fact that the new test fails : NameError: global name 'rin_two_turns' is not defined). It's true that we had to change significantly the structure, but that was the price to pay to recover to original speed (end even slightly better). The interface part of the integrators is much cleaner than before and is identical fo Python and Matlab.
I still have a question: as in Matlab, “atpass" returns the particle coordinates at each turn. But unlike Matlab, the input argument “rin” is modified in-place. We can chose either to keep it like this, and then an empty “refpts” argument would mean “no output at all”, which makes sense, the final coordinates being in “rin”, or to keep the input argument unchanged by internally making a copy and simulating the Matlab behaviour. I have no preference ! 

So OK for merging into the main branch, if you checked everything !

trackFunction becomes the entry point in both languages, passFunction may disappear in Python, however we have to keep it as alternate entry point in Matlab since users may have developed their own integrators

Laurent

**Comment by willrogers** [comment]
Sorry about the test - I have fixed that now.

I can't make `load_mat.py` run against the test file `atmat/atmatch/ExampleATMATCH/dba.mat`.  I get the following error:

```[  1.00000000e-06   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00]
Error in tracking element 10
Traceback (most recent call last):
  File "load_mat.py", line 55, in <module>
    at.atpass(m, rin, 1)
RuntimeError: No trackFunction in BndMPoleSymplectic4E2Pass.so
```

**Comment by lfarv** [comment]
Who’s going to convert BndMPoleSymplectic4E2Pass ?

**Comment by willrogers** [comment]
Well, indeed, my turn to do some work.  

It's no big deal, just I don't have a complete lattice I can test against right now.

**Comment by willrogers** [comment]
> I still have a question: as in Matlab, “atpass" returns the particle coordinates at each turn. But unlike Matlab, the input argument “rin” is modified in-place. We can chose either to keep it like this, and then an empty “refpts” argument would mean “no output at all”, which makes sense, the final coordinates being in “rin”, or to keep the input argument unchanged by internally making a copy and simulating the Matlab behaviour. I have no preference !

I don't see any reason to differ from what Matlab does here.

**Comment by lfarv** [comment]
I don’t know why this DBA example uses the “E2” method… Nicola started with the pass methods effectively used in our lattice, but there are still a lot to do. It can be done when it becomes necessary…

Concerning “atpass”: as you know, I would like to keep both versions similar, mainly to make it easier to switch from one to the other. However, Python has some nice features (keyword arguments for instance), and possibly a few things could possibly be better organised, so it is still possible to change things: pyat is not tied by the “compatibility” issue ! To be seen on a case-by-case basis !

Another point is: what’s next ? You brought the engine, by AT is thousands of lines of Matlab code. I was thinking of “atlinopt” and a few convenience routines to extract/modify lattice parameters (atgetcells, atgetfieldvalues, atsetfieldvalues…). Do you already have plans ?

Laurent

**Comment by willrogers** [comment]
I adapted `BndMPoleSymplectic4E2Pass` and it works with the test lattice.  Please check that it looks like you expect.

**Comment by willrogers** [comment]
If so, I will merge this branch.

**Pull request merged**
