### PR TITLE
Python build

### PR DESCRIPTION
**Pull request by willrogers**
Use the python build system to build the integrators.  This gives hope of a cross-platform build, although I have not tested on Windows.

### CODE REVIEW

**Comment by willrogers** [comment]
@lfarv @bnash @carmignani

This branch allows building pyat using the Python build mechanism.  It has two advantages:

* On Linux, it uses Python to locate the numpy dependencies, making the build easier on different distributions, and meaining we don't need a Makefile
* I have now adapted it so that it builds on Windows as well

There are plenty of things to discuss about this and tidy up but I hope we can agree that this is a good way to build...

**Comment by lfarv** [comment]
I get lots of warnings with the new headers:

-------------------------
In file included from /Volumes/machfs/laurent/dev/python/wr/atintegrators/AperturePass.c:1:
/Volumes/machfs/laurent/dev/python/wr/atintegrators/at.h:22:9: warning: 'INFINITY' macro redefined
      [-Wmacro-redefined]
#define INFINITY pinf
        ^
/usr/include/math.h:68:9: note: previous definition is here
#define INFINITY    HUGE_VALF
        ^
In file included from /Volumes/machfs/laurent/dev/python/wr/atintegrators/AperturePass.c:1:
/Volumes/machfs/laurent/dev/python/wr/atintegrators/at.h:24:9: warning: 'NAN' macro redefined
      [-Wmacro-redefined]
#define NAN dnan
        ^
/usr/include/math.h:60:15: note: previous definition is here
#   define    NAN          __builtin_nanf("0x7fc00000")
              ^
/Volumes/machfs/laurent/dev/python/wr/atintegrators/AperturePass.c:40:1: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
initAperturePass() {};
^
/Volumes/machfs/laurent/dev/python/wr/atintegrators/AperturePass.c:40:21: warning: control reaches
      end of non-void function [-Wreturn-type]
initAperturePass() {};
-------------------------
This is easy to solve by protecting the definition on NAN and INFINITY.
I do not see the use of the new entry point in all integrators. Matlab on Windows does not need it to load dynamically the trackFunction.

And I get a more critical error in setup:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    install_location = dist.command_obj['install'].install_platlib
KeyError: 'install'


Laurent

**Comment by willrogers** [comment]
Very quick.

The new entry point `init*Pass()` appears to be needed in order to persuade Python on Windows to build the extension.  I'm not certain.

There are warnings - some can be corrected as you have said.

I have solved the initial problem with `setup.py`, but I expect there is still a better way to do this.

**Comment by willrogers** [comment]
Although it probably will still fail because I haven't adapted all the pass methods for this new build ...

**Comment by willrogers** [comment]
It does build on Linux.  I deduce that you are on a Mac so I'm not sure.  It will fail on Windows until all pass methods are adapted.

**Comment by lfarv** [comment]
I am building (trying to…) on debian8 / python 2.7.9 !

**Comment by willrogers** [comment]
I thought that `/Volumes/machfs` looked like a Mac.

Let me know if I can help.  I am keen to pursue this because I think it offers the easiest way to a cross-platform build.

**Comment by lfarv** [comment]
The last version of setup.py works on both debian8 and MacOSX.
All the integrators now install in the "platlib" directory, together with "at.so". This directory may be rather crowded. Is it possible to pack "pyat" in a package, which would make the installation cleaner ?

**Comment by lfarv** [comment]
Concerning the additional entry point: 

- it still generates a warning on linux:
`/mntdirect/_machfs/laurent/dev/libraries/at/atintegrators/AperturePass.c:40:6: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void initAperturePass() {};`
just because it's missing "void" as argument
- it should be made python3-compatible and compiler-friendly by using the same macros as in at.c
- it should be protected by a `defined(PYAT) && defined(_WIN32)` clause to limit the pollution,
- if it is possible to use the same module name for all the integrators (why not since they are compiled independently), it could be moved to "atelem.c", to keep the pass methods intact,
- finally, is it absolutely necessary ? Does setup.py on Windows scan the contents of all C-files to look for an init function and compare it with the file name ?

Anyway, the new build method is really convenient !

**Comment by lfarv** [comment]
About the modified headers:

"at.h" is not intended to be used on "converted" pass methods (all references to mxXXX should have disappeared). The Windows section newly added could be moved to atelem.c, in the PYAT section.

**Comment by willrogers** [comment]
Shall we merge this branch to save doing too much development on the one branch?

We can continue to optimise the build mechanism.

**Comment by lfarv** [comment]
No objection for the merge: python-build is working for me !  I have been working on the Matlab side, which is normally decoupled from what you are doing, but it's difficult switching branches every time…
I keep my concerns about the headers and the fake module initialisation function for the future.

**Pull request merged**
