### PR TITLE
Synchronise matlab changes

### PR DESCRIPTION
**Pull request by willrogers**
From the `lfar` branch.

### CODE REVIEW

**Comment by lfarv** [comment]
Still problems with matlab compilation on Windows. I 'm looking at that…

**Comment by lfarv** [comment]
After merging from windows-build and fixing some details, I have the Matlab version running on Linux, MacOSX and Windows, and the Python version running on Linux and MacOSX (I cannot test on Windows).

**Comment by willrogers** [comment]
The `_WIN32` section found its way back into `at.h`.  Was this intentional?

**Comment by lfarv** [comment]
`at.h` needs a definition of NaNs and Infinity if Matlab (`mex.h`) is not used. It did not have a special case for windows until you pointed out this tricky "DECLSPEC_SELECTANY" definition !

**Pull request merged**
