### PR TITLE
Python packages

### PR DESCRIPTION
**Pull request by willrogers**
This branch is for rearranging the Python packages @lfarv.

### CODE REVIEW

**Comment by willrogers** [comment]
Just `git checkout -b python-packages` from your build-tidying branch and use that branch to push here.

**Comment by lfarv** [comment]
I am a bit lost: where have the modified headers gone ?
Otherwise, concerning the modified setup.py, I have no means to test it on Windows, so please have a look.

**Comment by willrogers** [comment]
The proposal here is:

```
import pyat
import pyat.atpass
import pyat.atintegrators
import pyat.load_mat
```
I would prefer:
```
import at
import at.pass
import at.integrators
import at.load_mat
```

We already know we're in Python we can import `at` not `pyat`, but there are other examples like Numpy that include the py, so we could keep `pyat` as the package name if you prefer.

**Comment by willrogers** [comment]
All the header changes should now be merged into both `pyat` and this branch.

I can only test Windows at home, so I will do that when I get a chance.

**Comment by lfarv** [comment]
I agree with your proposal. I did not look too much yet at the internal package organisation, with the lot of expected new modules. My first goal was to clean the site-packages directory where integrators were mixed with completely unrelated packages. Note that the (py)at.integrators is an fake package: nothing there can be imported, it is just a repository for the dynamically-loaded libraries.

I just tested the "no-python, no-mex" use of the integrators and found an issue: I am compiling with Visual Studio 2013, and it seems that this compiler now follows the C-standard: in `atcommon.h`, the _WIN32 section gives errors and I have to switch to the non-_WIN32 section to get things compiled. So we need to moderate the _WIN32 test with some compiler version info. I have no idea of how to do that…

**Comment by willrogers** [comment]
Could we create a README for how to build in different ways?

That would help me test the VS2013 problem.

**Comment by lfarv** [comment]
My VS2013 project is out of the repository, it lists a number of integrators and builds a shared library (dll) available for a few applications. Apart from distributing the project itself, I do not know how to document this, and it's probably not worth it.
Now for Python, distutils looks like the only reasonable way of building pyat, and I found this correlation between Python versions and compatible Windows compilers:
[https://wiki.python.org/moin/WindowsCompilers](https://wiki.python.org/moin/WindowsCompilers)
Apparently one could look at the 3 VSC++ versions (9, 10 and 14) and see how they behave with respect to the C standards (math.h). Visual Studio 2013 is apparently version 12, not listed as compatible with distutils… I'll look for predefined macros allowing to identify  the complier version.

**Comment by willrogers** [comment]
> I do not know how to document this, and it's probably not worth it.

OK, that's fine.

I haven't really tackled Python 3 yet.  The shared object files get additional parts in their names that will need additional logic to load dynamically: 

```
AperturePass.cpython-35m-x86_64-linux-gnu.so
```

**Comment by lfarv** [comment]
Python 3.4 works well on MacOSX, and I found the same problem in file names on Linux

**Comment by lfarv** [comment]
All looks fine here with Python 2.7 and Python 3.4, on both linux and MacOSX. What about "at" / "pyat" ? Do you want to switch ?

**Comment by willrogers** [comment]
I tried this, but I ran into a problem when installing and I don't understand it.

**Comment by willrogers** [comment]
OK, this works for me on Linux with the renamed packages.

Unfortunately I am having problems passing string macros into the C code on both Linux and Windows, so the Windows Python build is currently broken.  I will fix this when I get a chance.

I did not originally think this was likely, but now I hope we will be able to upload versions of pyat to [Pypi](https://pypi.python.org/pypi) by uploading binary 'wheels'.  This will take some more work but would be worth it.  It would mean that users could `pip install pyat` and be able to use it with very little effort.

I'm happy to merge this now.

**Pull request merged**
